/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.aplicacion.logica.productos.Medicamento;
import org.junit.Assert;
import org.junit.Test;

public class AppTest {
    @Test
    public void MedicamentoFuncionaTest(){
        String nombreCientifico = "Aspirina 1-2-3";   
        Medicamento pruebaMedicamento = new Medicamento(nombreCientifico);
        
        Assert.assertEquals(pruebaMedicamento.getNombreCientifico(), nombreCientifico);
    }
}
