/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.*;

import java.util.ArrayList;

public class AppTest {
    @Test
    public void MedicamentoFuncionaTest(){
        String nombreCientifico = "Aspirina 1-2-3";   
        Medicamento xd = new Medicamento(nombreCientifico);
        
        
    }
}
